NumPy is a package for scientific computing in Python.
It implements an object to represent N-dimensional arrays (vectors, matrices and higher dimensional matrices).
It also has linear algebra functions and random number generators.

Why do we need Numpy?
Python is a dynamically typed language, it infers the type of a variable at runtime.
This means that when Python store variables in memory, it not only stores the variable's value, but also its type.
Then, when we perform a computation, like adding two variables ($x+y$), Python looks up the type of $x$ and the type of $y$, and applies the definition of $+$ to those types if it makes sense to do so. If those types are integers, for example, then Python performs an integer addition.
However, if the type of $x$ is inteter, but $y$ is a list, then the operation is not defined and Python will raise an exception (error).
This type of checking is called a runtime type check.

The runtime type check makes programming in Python a pleasure, since you do not have to worry about types all the time.
However, it does lead to inefficiencies when we start performing operations on large datasets.
Numpy solves those inefficiencies.

Numpy introduces a new type of list, called a numpy `array`.
In an array, the type of all elements is the same.
This has two benefits.
First, the type is only stored once, so performing operations with numpy is much faster than with Python lists.
Second, since all elements have the same type, their position in the memory is easy to compute.
This means that accessing random elements in a numpy array is quick.

Numpy also provides a set of operations for numpy array, all implemented in C.
Arrays are not required to be 1 dimensional, so the class can also deal with matrices and higher dimensional arrays.
Numpy is the base of other higher-level packages, like `pandas` and `scipy`.




# Install



Numpy can be installed with `pip`.
After activating your environment in the terminal, run:



In [1]:
pip install numpy


The following command must be run outside of the IPython shell:

    $ pip install numpy

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


Now `numpy` is available for Python and can be imported with:



In [1]:
import numpy

All of the numpy functionality can now be accessed via the object `numpy`.

You will often see the following command being used:



In [2]:
import numpy as np

Which makes the `numpy` functionality available via `np`.
This is often used because it requires less typing to use numpy.




# Basics



To create a matrix with numpy we run:



In [6]:
matrix = np.array([[1,2,3,4],[4,5,6,7]])
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


This creates a new matrix with dimensions 2 by 4.



In [10]:
print(matrix[:,2:])
range(0,10)
print(matrix[:,2:-1])
print(matrix[:,[1,3]])

[[3 4]
 [6 7]]
[[3]
 [6]]
[[2 4]
 [5 7]]


The elements of the matrix can be accessed by using its indices.
Since the matrix has 2 dimensions, we need to give it two indices: an index for the row and an index for the column. Remember that in Python the indexing starts at 0.



We can use `:` to slice the matrix and obtain all values of a certain row or of a certain column:



We can also select specific columns or rows:



Like the built-in function `range`, numpy also provides a way to generate a sequence of numbers with the function `np.arange`:



In [11]:
range(0,10)
print(type(np.arange(0,10)))

<class 'numpy.ndarray'>


We can reshape this vector into a matrix:



In [13]:
vec = np.arange(20)
matrix = vec.reshape(4,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


We can also get the type of the values stored in the matrix:



In [14]:
print(matrix.dtype)

int32


Observe that the `np.array` takes a list of numbers as input, it does not take numbers as separate inputs:



In [15]:
np.array([[1],[2]])

array([[1],
       [2]])

If a list of lists is given, then we get a two-dimensional array:




# Data Types



The data type of values stored in a matrix are usually inferred when the values are assigned:



In [17]:
matrixfl= np.array([2.3,4.5,6.66])
print(matrixfl)

[2.3  4.5  6.66]


The first matrix has the type `int64` and the second matrix has the type `float64`.
Notice that if we try to change a value in the first matrix to a float, it will be implicitly converted to an integer:



In [18]:
matrixfjk = np.array([[1,2],[3,4]],dtype = 'float_')

We can specify the type of data when we first create the matrix:



The matrix is initialized with integers, but we specify the type to be a float, so the values are implicitly converted to floats.

The most common data types for numbers are:

| Data Type|Description|
|---|---|
| int\_|default integer type (usually int64)|
| float\_|default float type (usually float64)|
| complex\_|default complex type (usually complex128)|
| bool\_|default boolean type (uses a byte)|
|---|---|
| int<bytes>|where <bytes> can be 8, 16, 32 or 64|
| uint<bytes>|unsigned integer|
| float<bytes>||
| complex<bytes>||

Remember that defining a data type will convert the initial values  to the defined type:



In [19]:
matrix = np.array([[0,1],[True,False]],dtype = 'bool_')
print(matrix)

[[False  True]
 [ True False]]


If the values cannot be converted, an error is raised:



The command raises a `ValueError` and informs us that the string 'abc' cannot be converted to a float.

It is also possible to store strings in numpy arrays (matrices):



In [22]:
names = np.array(['a','b','c'],dtype = '<U20')
print(names,names.dtype)
names[0] = 'dsds'
print(names)

['a' 'b' 'c'] <U20
['dsds' 'b' 'c']


Notice that the type is actually "<U1". The "U" stands for "unicode string" and "1" is the number of characters.
Since all values passed to the `np.array` constructor have just 1 character, numpy assumes all data that we will store on this matrix will have a single character.
This might not be the case, and if we try to store a bigger string:



In [1]:
#matrix = np.array([{},{},{}])

Instead of storing the entire string, only the first character was stored.
We can let numpy know that we need more space in memory by defining how many characters we need:



Now we can store 100 characters in each element of the matrix.

Numpy can handle other data types, even objects:



In this case the data type is `object`.

The complete documentation on specifying data types (`dtype`) can be found [here](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#arrays-dtypes).
Arrays can also hold more than one type, details on how to hanlde multiple types can be found [here](https://docs.scipy.org/doc/numpy/user/basics.rec.html#module-numpy.doc.structured_arrays).




# Empty and Pre-Filled Arrays



On many cases we will want to create an empty array and populate as the code is executed.
We can create arrays pre-filled with ones or zeros via:



In [31]:
ones = np.ones((4,5))
print(ones)
zeros = np.zeros((4,5))
print(zeros)
sa = np.full((4,5),'a')
print(sa)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a']]


The functions `np.ones` and `np.zeros` takes a tuple, which defines the shape of the matrix to be created.

The function `np.empty` creates an "empty" matrix of the given shape and data type:



The matrix is filled with whatever values are in the memory.
If you use this command make sure all values are correctly replaced, otherwise you may run into bugs.

It is also possible to pre-fill a matrix with any given value:




# Operations



Arithmetic operations with numpy arrays are always <span class="underline">element wise</span>.



Notice that `**` is the same as `pow(c,2)`.

Comparisons are also done element wise:



In [33]:
a = np.array(range(0,10))
print(a >=5)
print(np.sum(a>=5))

[False False False False False  True  True  True  True  True]
5


Booleans can be used to recover elements of an array:



In [34]:
print(a[a>=5])

[5 6 7 8 9]


You can recover the indices that satisfy a condition with the `np.where` function:



In [35]:
indices = np.where(a>=5)
print(indices)
print(a[indices])

(array([5, 6, 7, 8, 9], dtype=int64),)
[5 6 7 8 9]


It is possible to manipulate all elements of an array and accumulate the values:



In [40]:
returns = np.random.random((78,3))
#print(returns)
returns /= 100
# print(returns)
RV = np.sum(returns**2, axis=0)
print(RV)


[0.00241851 0.00284123 0.00264398]


The `np.random.random` is a function that generates random values in the interval $[0, 1)$.
The `np.sum` function accumulates over elements in an array by summing them.
Calling `np.sum` without the `axis` argument will sum all of the elements in a matrix, resulting in a single value.
The keyword argument `axis=0` instructs the sum to occur along the rows.
Numpy provides many universal mathematical functions, such as `np.sqrt` for computing the square root of a number (remember, element wise).

We can find the minimum and maximum values in an array:



In [41]:
np.min
np.max
np.argmin #the index of minimum value
dir(np.random)
np.eyes()

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

Numpy also implements matrix operations:



In [42]:
a = np.eye(2)
print(a)
b = np.full((2,3),3)
print(a@b)

[[1. 0.]
 [0. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [43]:
dir(np.linalg)
OLS_beta = np.linalg.inv(X.T@X) @(X.T@X)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'absolute_import',
 'cholesky',
 'cond',
 'det',
 'division',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'info',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'print_function',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

A table that compares commands in Matlab to commands in Numpy is available [here](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html).
A good overview of many numpy features is available [here](https://docs.scipy.org/doc/numpy/user/quickstart.html#quickstart-tutorial).

