Exercise1A

Notion: For the sake of simplicity, I only did exercise on one stock HD in the report. One can import VZ5min.csv if he or she wants to do the exercise on stock VZ.

In [1]:
import numpy as np
# dtype={'names': ('date', 'time', 'price'), 'formats': ('int_', 'int_', 'float_')}

def importStock(path):
    return np.loadtxt(path,dtype={'names': ('date', 'time', 'price'), 'formats': ('int_', 'int_', 'float_')},delimiter = ',',usecols=(0,1,2))

# data = importStock('Data/SPY.csv')
data= importStock('C:\\Users\wc145\ECON672\Projects\Data\HD5min.csv')

Exercise1B

In [2]:
from datetime import datetime
# now datetime can be used

Notion: len(data) is too large for my computer to handle so I choose 10000 to present.

In [52]:
def getDatetime(data):
    dt = []
    for i in range(10000):     
    #for date, time in zip(data['date'],data['time']):
    #for date in data['date']:
        date_str = str(data['date'][i])
        year = int(date_str[:4])
        month = int(date_str[4:6])
        day = int(date_str[6:])
    #for time in data['time']:
        time_str = str(data['time'][i])
        hour = int(time_str[:-2])
        minute = int(time_str[-2:])
        dt.append(datetime(year, month, day, hour, minute))
    return dt

dt = getDatetime(data)
print(dt)

[datetime.datetime(2007, 1, 3, 9, 35), datetime.datetime(2007, 1, 3, 9, 40), datetime.datetime(2007, 1, 3, 9, 45), datetime.datetime(2007, 1, 3, 9, 50), datetime.datetime(2007, 1, 3, 9, 55), datetime.datetime(2007, 1, 3, 10, 0), datetime.datetime(2007, 1, 3, 10, 5), datetime.datetime(2007, 1, 3, 10, 10), datetime.datetime(2007, 1, 3, 10, 15), datetime.datetime(2007, 1, 3, 10, 20), datetime.datetime(2007, 1, 3, 10, 25), datetime.datetime(2007, 1, 3, 10, 30), datetime.datetime(2007, 1, 3, 10, 35), datetime.datetime(2007, 1, 3, 10, 40), datetime.datetime(2007, 1, 3, 10, 45), datetime.datetime(2007, 1, 3, 10, 50), datetime.datetime(2007, 1, 3, 10, 55), datetime.datetime(2007, 1, 3, 11, 0), datetime.datetime(2007, 1, 3, 11, 5), datetime.datetime(2007, 1, 3, 11, 10), datetime.datetime(2007, 1, 3, 11, 15), datetime.datetime(2007, 1, 3, 11, 20), datetime.datetime(2007, 1, 3, 11, 25), datetime.datetime(2007, 1, 3, 11, 30), datetime.datetime(2007, 1, 3, 11, 35), datetime.datetime(2007, 1, 3, 11,

Exercise1C

In [4]:
def getReturns(data, N, T):
    re = []
    for t in range(T):
        for i in range(N-1):
            re.append(data['price'][N*t+i+1]/data['price'][N*t+i])
    ret = np.log(re)
    ret = ret.reshape((T,N-1))
    return ret
    
N = 78
T = 2769
ret = getReturns(data, 78, 2769)
print(ret)

[[ 0.00604963 -0.001207    0.00409787 ...  0.00024328  0.
  -0.00024328]
 [-0.00196223  0.00636321  0.         ... -0.00147783  0.00098546
  -0.00147856]
 [ 0.00395062 -0.00197336 -0.00074102 ... -0.00025154  0.00401708
  -0.00301129]
 ...
 [-0.00294211  0.00068376  0.00105103 ...  0.00015768 -0.00042054
  -0.00026293]
 [-0.00099777 -0.0014196  -0.00015786 ... -0.00026358  0.00031629
   0.        ]
 [ 0.00073649  0.0007885   0.00084038 ...  0.00031554 -0.00115747
  -0.00121151]]


Exercise1D

In [5]:
def getRV(ret):
    rv = np.sum(ret**2,axis=1)
    rv = np.transpose(rv)
    return rv
    
RV = getRV(ret)
print(RV)

[1.89178814e-04 1.36982229e-04 1.23845375e-04 ... 3.16607902e-05
 1.52703800e-05 2.40689990e-05]


Exercise1E

In [6]:
import math
math.pi

3.141592653589793

In [7]:
def getBV(ret,N,T):
    bv =[]
    for t in range(T):
        bvt = 0.0
        for i in range(1,N-1):
            bvt = bvt + abs(ret[t][i])*abs(ret[t][i-1])
        bvt =(math.pi/2)*bvt
        bv.append(bvt)
    return bv

BV = getBV(ret,N,T)
print(BV)

[0.00017086106187625698, 0.0001245421725134288, 0.00011033771680880349, 7.61419693339421e-05, 0.00012362750287874178, 9.671350016975504e-05, 7.840564830128408e-05, 6.426490175507074e-05, 6.203191715671081e-05, 4.2950201212192145e-05, 0.00010424393436956845, 8.071997293262208e-05, 0.00010596931762411153, 8.396244701063796e-05, 3.326416352525136e-05, 6.510824540450905e-05, 8.014680692923054e-05, 6.364122072571914e-05, 7.446960511243648e-05, 6.420036446552485e-05, 9.248711079440453e-05, 7.581432119385949e-05, 7.056976696474624e-05, 4.7684342203607606e-05, 3.7459424599714283e-05, 4.6076951168844775e-05, 5.235995328203103e-05, 9.588720614734427e-05, 4.641857229568485e-05, 5.595180651336517e-05, 7.793105937361862e-05, 5.74293860951463e-05, 0.00018128749626973695, 8.7150030842055e-05, 6.421901962618455e-05, 6.126215534563911e-05, 7.846309422232825e-05, 0.00017628637460173724, 0.0002574411759699945, 0.0002976993077778552, 5.431745212059071e-05, 0.00017406542913088317, 9.067955982700153e-05, 6.

Exercise1F

In [8]:
def getTOD(ret,N,T):
    tod =[]
    b = np.empty((78), dtype='float_')
    for i in range(1,N-1):
        bs = 0
        for t in range(T):
            bs = bs + abs(ret[t][i]*ret[t][i-1])
        bs = bs/T
        b[i] = bs
    b[0]=b[1]
    for i in range(N-1):
        tod.append(((N-1)*b[i])/np.sum(b))
    return tod

tod = getTOD(ret,N,T)
print(tod)

[4.541501603569549, 4.541501603569549, 2.958578351127797, 2.4019275108096694, 2.0956188524265, 2.293338347485494, 2.2883527069606138, 1.786910852391851, 1.5515178492088255, 1.3753982012562131, 1.2912719437904132, 1.2763290685231352, 1.1833586745434288, 1.230446928033169, 1.190363330220001, 1.0648478639503285, 0.9429055696618419, 1.01840887160104, 0.9783071708576963, 0.9158477844680921, 0.8132400212890736, 0.7868903243413732, 0.8241180517083958, 0.8025071833198762, 0.7584400174831855, 0.6870739159510012, 0.6460091171912556, 0.6671120744981986, 0.6913599302851217, 0.6522727141281637, 0.6271129990523236, 0.5232457543812523, 0.5641260365716593, 0.581250396734092, 0.615495086514658, 0.5773818305455205, 0.5776076459115284, 0.5082098510079892, 0.5035448481879462, 0.5115249665125937, 0.5177177415795833, 0.5379604488463392, 0.5614643628200543, 0.5872964324916178, 0.5375310307296617, 0.5408529018304853, 0.5240672837821765, 0.5921100937667834, 0.5937830391458307, 0.6014805756449241, 0.57314220816

Exercise1G

In [9]:
def separateReturns(ret,alpha=5):
    cut = np.empty((T, N-1), dtype='float_')
    rc = np.zeros((T, N-1), dtype='float_')
    rd = np.zeros((T, N-1), dtype='float_')
    nd = 0
    # compute jump threshold
    for t in range(T):
        for i in range(N-1):
            cut[t][i] = alpha*((1/(N-1))**(0.49))*np.sqrt(tod[i]*BV[t])
    # separate diffusive from jump returns
    # return diffusive and jump returns
    for t in range(T):
        for i in range(N-1):
            if abs(ret[t][i])<= cut[t][i]:
                rc[t][i]= ret[t][i]
            else:
                rd[t][i]= ret[t][i]
                nd = nd+1
    return rc, rd, nd

rc, rd, nd = separateReturns(ret)
print(rc)
print(rd)
print(nd)

[[ 0.00604963 -0.001207    0.00409787 ...  0.00024328  0.
  -0.00024328]
 [-0.00196223  0.00636321  0.         ... -0.00147783  0.00098546
  -0.00147856]
 [ 0.00395062 -0.00197336 -0.00074102 ... -0.00025154  0.00401708
  -0.00301129]
 ...
 [-0.00294211  0.00068376  0.00105103 ...  0.00015768 -0.00042054
  -0.00026293]
 [-0.00099777 -0.0014196  -0.00015786 ... -0.00026358  0.00031629
   0.        ]
 [ 0.00073649  0.0007885   0.00084038 ...  0.00031554 -0.00115747
  -0.00121151]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
59


Exercise1H

In [10]:
def getQIV(rc):
    QIV = np.empty((T),dtype='float_')
    for t in range(T):
        rcsum = np.sum(rc[t]**4)
        QIV[t]= ((N-1)/3)*rcsum
    return QIV

QIV = getQIV(rc)
print(QIV)

[6.23220707e-08 5.04562777e-08 2.61111218e-08 ... 2.41785112e-09
 3.02902554e-10 6.10600046e-10]


Exercise2

Exercise2A

In [11]:
def getRVWeek(RV):
    # compute all RVw
    RVw = np.zeros((T),dtype='float_')
    for t in range(21,T):
        RVw[t] = np.sum(RV[t-4:t+1])/5
    return RVw
        
def getRVMonth(RV):
    # compute all RVm
    RVm = np.zeros((T),dtype='float_')
    for t in range(21,T):
        RVm[t] = np.sum(RV[t-21:t+1])/22
    return RVm


RVw = getRVWeek(RV)
RVm = getRVMonth(RV)

model_input = np.ones((T-22+1, 5), dtype='float_')
model_input[:, 1] = RV[21:]
model_input[:, 2] = RVw[21:]
model_input[:, 3] = RVm[21:]
model_input[:, 4] = np.sqrt(QIV[21:])*RV[21:]
print(model_input.shape)
columns = model_input.shape[1]
print(model_input)

(2748, 5)
[[1.00000000e+00 7.30544883e-05 7.81579963e-05 9.26947561e-05
  5.94243982e-09]
 [1.00000000e+00 6.99838109e-05 8.05751608e-05 8.72768014e-05
  4.70278671e-09]
 [1.00000000e+00 5.49235133e-05 7.37269443e-05 8.35468598e-05
  2.95940775e-09]
 ...
 [1.00000000e+00 3.16607902e-05 4.67839671e-05 8.02955900e-05
  1.55681328e-09]
 [1.00000000e+00 1.52703800e-05 3.31276275e-05 7.79463091e-05
  2.65767158e-10]
 [1.00000000e+00 2.40689990e-05 2.93446740e-05 7.13607708e-05
  5.94752733e-10]]


Exercise2B

In [12]:
def OLS(Y, X):
    # return beta estimate from OLS
    # np.linalg.inv computes the inverse of a matrix
    # remember that in numpy * is elementwise multiplication
    # the symbol for matrix multiplication is @, as in X.T@X
    # X.T is the tranpose of X
    beta = np.linalg.inv(X.T@X)@X.T@Y
    return beta

In [13]:
def forecastError(Y, X, Y_next, X_next):
    # computes the forecast error
    # estimate beta
    beta = OLS(Y,X)
    Y_forecast = X_next@beta
    return (Y_next - Y_forecast)**2

In [14]:
error = {'AR1': 0.0, 'HAR1': 0.0, 'ARQ1': 0.0, 'HARQ1': 0.0, 'NoChange': 0.0}
window_size = 1000
# rolling window + 1-step-ahead forecast
for S in range(window_size,T-22):
    window_x = slice(S - window_size, S)
    window_y = slice(S - window_size + 1, S + 1)
    # AR(1)
    error['AR1'] += forecastError(model_input[window_y, 1],
                                  model_input[window_x, 0:2],
                                  model_input[S+1, 1],
                                  model_input[S,0:2])
    # HAR(1)
    error['HAR1'] += forecastError(model_input[window_y,1],
                                   model_input[window_x, 0:4],
                                   model_input[S+1,1],
                                   model_input[S,0:4])
    # ARQ(1)
    Y_forecast = model_input[S,[0,1,4]] @ OLS(model_input[window_y,1],model_input[window_x,[0,1,4]])
    if Y_forecast > np.max(model_input[window_y,1]) or Y_forecast < np.min(model_input[window_y,1]) :
        Y_forecast = np.mean(model_input[window_y,1])
        error['ARQ1'] += (model_input[S+1,1] - Y_forecast)**2 
    else:
        error['ARQ1'] += forecastError(model_input[window_y,1],
                                   model_input[window_x,[0,1,4]],
                                   model_input[S+1,1],
                                   model_input[S,[0,1,4]])
    
    # HARQ(1)
    Y_forecast = model_input[S,:] @ OLS(model_input[window_y,1],model_input[window_x,:])
    if Y_forecast > np.max(model_input[window_y,1]) or Y_forecast < np.min(model_input[window_y,1]) :
        Y_forecast = np.mean(model_input[window_y,1])
        error['HARQ1'] += (model_input[S+1,1] - Y_forecast)**2 
    else:
        error['HARQ1'] += forecastError(model_input[window_y,1],
                                    model_input[window_x,:],
                                    model_input[S+1,1],
                                    model_input[S,:])
    # No Change
    error['NoChange'] += (model_input[S+1,1]-model_input[S,1])**2
print(error)

{'AR1': 5.5278367786205925e-05, 'HAR1': 4.66801489212861e-05, 'ARQ1': 4.1156598181634573e-05, 'HARQ1': 4.0519780632799934e-05, 'NoChange': 6.529217621917736e-05}


In [15]:
# compute and print MSE
total = len(model_input) - window_size 
print("{:^10}|{:^10}".format('Model','MSE'))
print(f"{'-'*21}")
for model, value in error.items():
    print(model,value/total)
print(f"{'-'*21}")

  Model   |   MSE    
---------------------
AR1 3.162378019805831e-08
HAR1 2.6704890687234608e-08
ARQ1 2.354496463480239e-08
HARQ1 2.3180652535926735e-08
NoChange 3.735250355788179e-08
---------------------


Exercise2C

In [16]:
# the absolute values of the MSE are very small and difficult to compare
# report the MSE relative to the MSE of the NoChange Model
total = len(model_input) - window_size
print("{:^10}|{:^20}".format('Model', 'Relative MSE'))
print(f"{'-'*31}")
[print(f'{model:^10}|{value/error["NoChange"]:^20.6f}')
 for model, value in error.items()]
print(f"{'-'*31}")

  Model   |    Relative MSE    
-------------------------------
   AR1    |      0.846631      
   HAR1   |      0.714942      
   ARQ1   |      0.630345      
  HARQ1   |      0.620592      
 NoChange |      1.000000      
-------------------------------


Exercise3A

In [34]:
import tensorflow as tf
# get default graph
# create model input (x) and model output (x)
x = tf.placeholder(tf.float32, [None, 5])
y = tf.placeholder(tf.float32, [None])
# create hidden layer
W1 = tf.Variable(tf.random_normal([5,10]))
S1 = tf.nn.relu(tf.matmul(x,W1))
# create last layer
W2 = tf.Variable(tf.random_normal([10,1]))
y_model = tf.matmul(S1,W2)

Exercise3B

In [47]:
# create loss function
loss = tf.reduce_mean(tf.squared_difference(y_model,y))
# create optimizer
train_one_step = tf.train.AdamOptimizer(learning_rate = 0.005).minimize(loss)


Exercise3C

Notion: I set epochs=20000 since I found MSE remained quite stable aftesr 15000.

In [48]:
def forecastNN(S, window_size=1000, epochs=20000, columns=5):
    # determine window size
    window_x = slice(S - window_size, S)
    window_y = slice(S - window_size +1, S+1)
    with tf.Session() as session:
        # initialize variables
        session.run(tf.global_variables_initializer())
        print(f'\n\nSTEP | MSE')
        for i in range(epochs):
            # do 1 step on gradient descent
            [_,MSE]= session.run([train_one_step, loss],feed_dict={
            x: model_input[window_x,:],
            y: model_input[window_y,1]
        })
            # print MSE every 500 epochs
            if i % 500 == 0:
                print(f'{i:^5}|{MSE:^4}')
        # model is done training, use it to forecast
        y_forecast = session.run(y_model, feed_dict={
            x: [model_input[S,:]]
        })
        # add a sanity filter
        if y_forecast > np.max(model_input[window_y,1]) or y_forecast < np.min(model_input[window_y,1]) :
            y_forecast = np.mean(model_input[window_y,1])
        return float(y_forecast)

Exercise3D

Notion: Forecasting 1748 days' MSE will cost too much time, So I randomly choose 50 days as a sample to get an avarage MSE.

In [59]:
import random

In [60]:
error['NN']=0
print("{:^10}|{:^10}|{:^10}|{:^20}|{:^10}".format(
    "Window", "Forecast", "Actual", "Cummulative Error", "MSE"))
window_size = 1000
a = []
k = 0
for j in range(0,51):
    a.append(random.randint(window_size, T-22))
for S in a:
    k += 1
#for S in range(1000,1002):
    y_forecast = forecastNN(S)
    # store error
    error['NN'] += (model_input[S + 1, 1] - y_forecast)**2
    # print message
    print(f'{S - window_size:^10}|{float(y_forecast):^10.6f}|{model_input[S + 1, 1]:^10.6f}'
          f'|{error["NN"]:^20.6f}|{error["NN"]/k}')

  Window  | Forecast |  Actual  | Cummulative Error  |   MSE    


STEP | MSE
  0  |141.92112731933594
 500 |0.415585994720459
1000 |3.625179306254722e-05
1500 |2.291372538820724e-06
2000 |2.27863029067521e-06
2500 |2.2618080492975423e-06
3000 |2.240039748357958e-06
3500 |2.2122897007648135e-06
4000 |2.1772636955574853e-06
4500 |2.133618409061455e-06
5000 |2.0798720470338594e-06
5500 |2.0145721464359667e-06
6000 |1.9364456420589704e-06
6500 |1.8448898799761082e-06
7000 |1.7403943957106094e-06
7500 |1.624913238629233e-06
8000 |1.5020768842077814e-06
8500 |1.3775194247500622e-06
9000 |1.2577128245538916e-06
9500 |1.1487010169730638e-06
10000|1.0540602488617878e-06
10500|9.733388424137956e-07
11000|9.022875246955664e-07
11500|8.354018063982949e-07
12000|7.691402856835339e-07
12500|7.03546845670644e-07
13000|6.416718747459527e-07
13500|5.877112698726705e-07
14000|5.452038180919772e-07
14500|5.156499014447036e-07
15000|4.978609808858891e-07
15500|4.885839075541298e-07
16000|4.84156316815642

14500|4.379494455974964e-08
15000|4.31187459071225e-08
15500|4.26049311386123e-08
16000|4.213438842270989e-08
16500|4.1937969541550046e-08
17000|4.1787007631910456e-08
17500|4.164905220704895e-08
18000|4.149836030364895e-08
18500|4.133854147880811e-08
19000|4.117963214866904e-08
19500|4.103000605937268e-08
   497    | 0.000208 | 0.000041 |      0.000000      |2.8809986580995873e-08


STEP | MSE
  0  |514.2592163085938
 500 |0.007639600429683924
1000 |1.554958316773991e-06
1500 |1.5349968407463166e-06
2000 |1.5080656794452807e-06
2500 |1.473176325816894e-06
3000 |1.4290827721197275e-06
3500 |1.3745180922342115e-06
4000 |1.3084628562864964e-06
4500 |1.230244947691972e-06
5000 |1.1388316352167749e-06
5500 |1.0371129519626265e-06
6000 |9.281330335397797e-07
6500 |8.16449983176426e-07
7000 |7.085206448209647e-07
7500 |6.112224468779459e-07
8000 |5.268358336252277e-07
8500 |4.5464605591405416e-07
9000 |3.947947959659359e-07
9500 |3.4949385963045643e-07
10000|3.208499492757255e-07
10500|3.003

8500 |5.3669346300466714e-08
9000 |5.257452428963916e-08
9500 |5.125091107061053e-08
10000|4.9679492519771884e-08
10500|4.784804730206815e-08
11000|4.5759151134916465e-08
11500|4.342692960790373e-08
12000|4.089178062827159e-08
12500|3.8194926332835166e-08
13000|3.538247028700425e-08
13500|3.2485615975019755e-08
14000|2.9544066748599107e-08
14500|2.6617396287065276e-08
15000|2.3814500593744015e-08
15500|1.1118219163108733e-06
16000|1.7369724446325563e-05
16500|1.866374077508226e-08
17000|1.782560410390488e-08
17500|1.7245127992282505e-08
18000|1.4933165459751763e-07
18500|1.656021630935811e-08
19000|1.6365078181479475e-08
19500|1.6230487176471797e-08
   628    | 0.000123 | 0.000070 |      0.000000      |1.9499910213815184e-08


STEP | MSE
  0  |389.43621826171875
 500 |0.0006556744920089841
1000 |2.2528324734594207e-06
1500 |2.2430510853155283e-06
2000 |2.229581923529622e-06
2500 |2.2117997104942333e-06
3000 |2.1885941805521725e-06
3500 |2.158723646061844e-06
4000 |2.120752014889149e-06

2500 |2.9897489639552077e-07
3000 |2.9763083375655697e-07
3500 |2.959149583148246e-07
4000 |2.9372969834184914e-07
4500 |2.9096776188453077e-07
5000 |2.874792244256241e-07
5500 |2.8316756583990355e-07
6000 |2.77790434211056e-07
6500 |2.712178854835656e-07
7000 |2.632020539294899e-07
7500 |2.53548080308974e-07
8000 |2.420510440970247e-07
8500 |2.2855768122553854e-07
9000 |2.129292653307857e-07
9500 |1.951793393573098e-07
10000|1.7542078012411366e-07
10500|1.540583696169051e-07
11000|1.3181444558085786e-07
11500|1.0981237608120864e-07
12000|8.940293128034682e-08
12500|7.202324070476607e-08
13000|5.868757924076817e-08
13500|4.966421585095304e-08
14000|4.433171696405225e-08
14500|4.163110745025733e-08
15000|4.0309465987320436e-08
15500|3.993156383330643e-08
16000|4.54040900876862e-06
16500|5.019812670070678e-05
17000|1.4327400776892318e-06
17500|3.859348362311721e-05
18000|3.7747071246485575e-08
18500|3.5959697015641723e-06
19000|3.741192955430961e-08
19500|3.72968678163943e-08
   1163   |

18000|1.8094068465757118e-08
18500|1.7919813188882472e-08
19000|1.7748103431358686e-08
19500|1.7585287892529777e-08
   586    | 0.000152 | 0.000096 |      0.000000      |1.6568125194430437e-08


STEP | MSE
  0  |173.63583374023438
 500 |1.4061377048492432
1000 |0.06609421968460083
1500 |0.00041379674803465605
2000 |4.386956788948737e-07
2500 |2.1519404924674745e-07
3000 |2.1485216450400912e-07
3500 |2.1442855313580367e-07
4000 |2.1388572690739238e-07
4500 |2.1319003451480967e-07
5000 |2.1230104607639078e-07
5500 |2.1116983361935127e-07
6000 |2.0973142511593323e-07
6500 |2.07913402050508e-07
7000 |2.0561850533340476e-07
7500 |2.027392582704124e-07
8000 |1.9913856874609337e-07
8500 |1.946683880760247e-07
9000 |1.8915002897301747e-07
9500 |1.8239960297705693e-07
10000|1.7423397480342828e-07
10500|1.6449659767658886e-07
11000|1.530805491256615e-07
11500|1.400079128188736e-07
12000|1.254744574907818e-07
12500|1.0991452370490151e-07
13000|9.403785838912881e-08
13500|7.879535957044936e-08
140

12500|5.145680148643805e-08
13000|4.5474930487898746e-08
13500|4.1826520913446075e-08
14000|3.991213404219707e-08
14500|3.8863568363467493e-08
15000|3.8324952100765586e-08
15500|3.783449287197982e-08
16000|3.73874300407806e-08
16500|7.453259627254738e-07
17000|3.693524064374287e-08
17500|3.6844809869762685e-08
18000|3.67495687214614e-08
18500|3.6654306256878044e-08
19000|3.656480984659538e-08
19500|3.648765911634655e-08
   1374   | 0.000090 | 0.000031 |      0.000001      |1.4931433660352893e-08


STEP | MSE
  0  |92.06285858154297
 500 |4.6316564805692906e-08
1000 |4.6273381570927086e-08
1500 |4.6218737281833455e-08
2000 |4.6134530862218526e-08
2500 |4.603506198463947e-08
3000 |4.589820079559104e-08
3500 |4.572936163071972e-08
4000 |4.550948062842508e-08
4500 |4.5229544554103995e-08
5000 |4.488074267783304e-08
5500 |4.443963419475949e-08
6000 |4.389104191204751e-08
6500 |4.322019719893433e-08
7000 |4.2411159029143164e-08
7500 |4.144208176626307e-08
8000 |4.0302420956095375e-08
8500 |3

7000 |3.824845771305263e-05
7500 |1.8457645637681708e-05
8000 |7.5395691965240985e-06
8500 |2.759077005975996e-06
9000 |1.1795959835581016e-06
9500 |7.84496194228268e-07
10000|6.78317860547395e-07
10500|6.18993510670407e-07
11000|5.723646836486296e-07
11500|5.379870344768278e-07
12000|5.157071996109153e-07
12500|5.031341174799309e-07
13000|4.966606752532243e-07
13500|4.932382466904528e-07
14000|4.911869382340228e-07
14500|4.898626002614037e-07
15000|4.890220566267089e-07
15500|4.884723807663249e-07
16000|4.881283643953793e-07
16500|4.878646109318652e-07
17000|4.875675472248986e-07
17500|4.872512704423571e-07
18000|4.869252165917715e-07
18500|4.86586031911429e-07
19000|4.862408786721062e-07
19500|4.85010104966932e-07
   221    | 0.000462 | 0.000099 |      0.000001      |1.8295594648315018e-08


STEP | MSE
  0  |209.43650817871094
 500 |1.006760612654034e-05
1000 |9.655801477492787e-06
1500 |9.262458661396522e-06
2000 |8.75297155289445e-06
2500 |8.130037713272031e-06
3000 |7.402963547065

1000 |9.852635685092537e-08
1500 |9.827443392396162e-08
2000 |9.792077548809175e-08
2500 |9.747460438802591e-08
3000 |9.688331203960843e-08
3500 |9.613739848646219e-08
4000 |9.517820132032284e-08
4500 |9.396809730333189e-08
5000 |9.247420962310571e-08
5500 |9.063336392500787e-08
6000 |8.838551934786665e-08
6500 |8.56949711192101e-08
7000 |8.252237648775917e-08
7500 |7.886958286462686e-08
8000 |7.476974417386373e-08
8500 |7.03098308463268e-08
9000 |6.55800533877482e-08
9500 |6.073138081319485e-08
10000|5.586925411193988e-08
10500|5.1023064884248015e-08
11000|4.615256088413844e-08
11500|4.1209332835023815e-08
12000|3.617612875927989e-08
12500|3.1193252425509854e-08
13000|2.648822317041777e-08
13500|1.3646487673213414e-07
14000|2.0725007487953917e-08
14500|1.8873270946073717e-08
15000|1.7144120789680528e-08
15500|1.5608961234647722e-08
16000|1.4768303024936813e-08
16500|1.454276787882236e-08
17000|1.4277972582021903e-08
17500|1.3976213963928785e-08
18000|1.3643627561066296e-08
18500|1.328

Exercise3E

Notion: 'NN' is kept because I ran the regression with it in the dictionary error and don't have time to rerun it in a new dictionary. 'NNreal' reports the real average MSE I got from neural network model while 'NN' has no meaning.

In [80]:
total = len(model_input) - window_size
total1 = 50
error1 = error['NN']
NNreal = 'NNreal'
print("{:^10}|{:^10}".format('Model','MSE'))
print(f"{'-'*21}")
[print(f'{model:^10}|{value/total}') for model, value in error.items()]
print(f'{NNreal:^10}|{error1/total1}')  
print(f"{'-'*21}")

  Model   |   MSE    
---------------------
   AR1    |3.162378019805831e-08
   HAR1   |2.6704890687234608e-08
   ARQ1   |2.354496463480239e-08
  HARQ1   |2.3180652535926735e-08
 NoChange |3.735250355788179e-08
    NN    |6.106270542391402e-10
  NNreal  |2.1347521816200346e-08
---------------------


In [82]:
# the absolute values of the MSE are very small and difficult to compare
# report the MSE relative to the MSE of the NoChange Model
total = len(model_input) - window_size
print("{:^10}|{:^20}".format('Model', 'Relative MSE'))
print(f"{'-'*31}")
[print(f'{model:^10}|{value/error["NoChange"]:^20.6f}')
 for model, value in error.items()]
print(f'{NNreal:^10}|{(error1/total1)/(error["NoChange"]/total):^20.6f}')
print(f"{'-'*31}")

  Model   |    Relative MSE    
-------------------------------
   AR1    |      0.846631      
   HAR1   |      0.714942      
   ARQ1   |      0.630345      
  HARQ1   |      0.620592      
 NoChange |      1.000000      
    NN    |      0.016348      
  NNreal  |      0.571515      
-------------------------------


At the first attempt, I found the neural network model didn't improve the forecast error. It may because the epochs are not large enough or learning rate and default weights are not wisely picked. The forecast error of NN model should be smaller than HARQ model since it's more complicated. Thus, in the second attempt, I set learning_rate equals to 0.005, which is a larger step than normal 0.001. The neural network model performs better than HARQ this time according to MSE. However, it took me a whole night to predict this small sample, which seems not so efficiency.